### PR TITLE
Update with new images and question answers

### PR DESCRIPTION
**Pull request by duckmoll**
Delete existing images and question answers when update.

### CODE REVIEW

**Comment by tangziyi001** [comment]
I'm actually thinking about everytime a user update the profile, we should create a new one for this user and still keep the old one (1 user -> N profile with different versions). The reason is that if we just drop old profile and images, and if the image was liked by someone else, we will basically loss the like action or crash the app when we try to get that image in banner.

**Comment by tangziyi001** [comment]
I'm ok with this change as long as we change the profile updates as "creation of a new version" instead of "deletion + creation", which can loss all reference from liked items

**Comment by duckmoll** [comment]
I think I understand your concern. So we should still keep the question answers and images information since they could still be liked even after they are deleted.

**Comment by tangziyi001** [comment]
Yes exactly.

**Comment by duckmoll** [comment]
Then I just need to cut the connection between AnswerQuestion, Images and Profiles, but keep users' connection, so front could still retrieve old images/answers via user and entity_id, but we use profile linked images/answers to show profiles.

**Comment by duckmoll** [comment]
Good Catch

**Comment by tangziyi001** [comment]
Yeah that would also be fine. In that case you probably don't want to cascade the image

**Comment by tangziyi001** [comment]
Awesome

**Pull request merged**
