### PR TITLE
Registered question models to admin

### PR DESCRIPTION
**Pull request by duckmoll**
- Registered superuser on local and tested admin page after runserver. #37 
- Changed spacing in admin files.
screen shot 2018-11-28 at 12 35 34 am

### CODE REVIEW

**Comment by tangziyi001** [comment]
better to take a screenshot as part of the test

**Comment by duckmoll** [comment]
Just updated the pull request.

**Comment by tangziyi001** [comment]
Not sure what do you mean by the model name will change. The model name looks good right now.

**Comment by duckmoll** [comment]
I see. I thought the ‘s’ comes from old migration files.

**Pull request merged**
