### PR TITLE
[easy] Add try...except around notification exception

### PR DESCRIPTION
**Pull request by tangziyi001**
This is to make sure we'll not return 500 when exception happens during notification
Screen Shot 2019-05-19 at 7 53 19 PM

### CODE REVIEW

**Comment by duckmoll** [comment]
So "like" works?

**Comment by tangziyi001** [comment]
@duckmoll Yeah verified in slack. However the notification failed. Is it because the instance id was not created for super user? (which is as expected if instance id is created during registration since admin never went through formal registration)

**Comment by tangziyi001** [comment]
The like can work if I merge the PR in ios repo, where I fixed a but in like action

**Comment by duckmoll** [comment]
Cool 👍

**Pull request merged**
